sources:
  - ../../Core
templates:
  - ../../Core/Autogeneration/AutoPublicInit.stencil
  - ../../Core/Autogeneration/ImagesTests.stencil
  - ../../Core/Autogeneration/AutoStoryboard.stencil
  - ../../Core/Autogeneration/AutoRouterTests.stencil
  - ../../Core/Autogeneration/AutoEquatable.stencil
output:
  ../../Core/Autogeneration
